# Generated by Django 3.2 on 2023-04-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_review_approved'),
        ('basket', '0002_alter_basketitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
